Syncing docker file for 87301

diff --git a/Dockerfile-minimal b/Dockerfile-minimal
--- a/Dockerfile-minimal
+++ b/Dockerfile-minimal
@@ -53,10 +53,12 @@ COPY --from=eclipse-temurin:17.0.14_7-jre-ubi9-minimal /opt/java/openjdk/ /opt/j
 ENV JAVA_HOME=/opt/java/openjdk
 
 RUN set -o pipefail \
-  && mkdir -m 777 -p client-tools/scm/90f3b724a \
-  && curl -f -s -L -o client-tools/scm/90f3b724a/scm https://app.harness.io/public/shared/tools/scm/release/90f3b724a/bin/linux/$TARGETARCH/scm || { echo "Failed to download scm"; exit 1; } \
+  && mkdir -m 777 -p client-tools/scm/c3c7406b3 \
+  && curl -f -s -L -o client-tools/scm/c3c7406b3/scm https://app.harness.io/public/shared/tools/scm/release/c3c7406b3/bin/linux/$TARGETARCH/scm || { echo "Failed to download scm"; exit 1; } \
   && curl -f -s -L -o $JAVA_HOME/bin/jattach https://app.harness.io/public/shared/tools/jattach/release/v2.2/bin/linux/$TARGETARCH/jattach || { echo "Failed to download jattach"; exit 1; } \
   && chmod +x $JAVA_HOME/bin/jattach \
+  && mkdir -m 777 -p client-tools/hcli/68e8ada \
+  && curl -f -s -L -o client-tools/hcli/68e8ada/hcli https://app.harness.io/public/shared/tools/hcli/release/68e8ada/bin/linux/$TARGETARCH/hcli \
   && chmod -R 775 /opt/harness-delegate \
   && chgrp -R 0 /opt/harness-delegate \
   && chown -R 1001 /opt/harness-delegate \
@@ -68,6 +70,7 @@ ENV CLIENT_TOOLS_DOWNLOAD_DISABLED=true
 ENV INSTALL_CLIENT_TOOLS_IN_BACKGROUND=true
 ENV PATH="$JAVA_HOME/bin:${PATH}"
 ENV PATH="$JAVA_HOME/bin/jattach:${PATH}"
+ENV PATH=/opt/harness-delegate/client-tools/hcli/68e8ada/:$PATH
 
 # Run the download-bc.sh script during build time
 RUN /opt/harness-delegate/download-bc.sh
