Syncing docker file for 86402

diff --git a/Dockerfile-minimal b/Dockerfile-minimal
--- a/Dockerfile-minimal
+++ b/Dockerfile-minimal
@@ -64,7 +64,7 @@ ENV PATH="$JAVA_HOME/bin/jattach:${PATH}"
 # Run the download-bc.sh script during build time
 RUN /opt/harness-delegate/download-bc.sh
 
-RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar
+RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar && [ $(stat -c%s delegate.jar) -ge 104857600 ] || (echo "Failed to download delegate.jar or delegate.jar is corrupted" && exit 1)
 
 USER 1001
 
diff --git a/Dockerfile-ubuntu b/Dockerfile-ubuntu
--- a/Dockerfile-ubuntu
+++ b/Dockerfile-ubuntu
@@ -49,8 +49,8 @@ RUN set -o pipefail \
   && curl -f -s -L -o client-tools/helm/v3.13.3/helm https://app.harness.io/public/shared/tools/helm/release/v3.13.3/bin/linux/$TARGETARCH/helm || { echo "Failed to download helm"; exit 1; } \
   && mkdir -m 777 -p client-tools/harness-helm-post-renderer/v0.1.5 \
   && curl -f -s -L -o client-tools/harness-helm-post-renderer/v0.1.5/harness-helm-post-renderer https://app.harness.io/public/shared/tools/harness-helm-post-renderer/release/v0.1.5/bin/linux/$TARGETARCH/harness-helm-post-renderer || { echo "Failed to download harness-helm-post-renderer"; exit 1; } \
-  && mkdir -m 777 -p client-tools/go-template/v0.4.8 \
-  && curl -f -s -L -o client-tools/go-template/v0.4.8/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4.8/bin/linux/$TARGETARCH/go-template || { echo "Failed to download go-template"; exit 1; } \
+  && mkdir -m 777 -p client-tools/go-template/v0.4.9 \
+  && curl -f -s -L -o client-tools/go-template/v0.4.9/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4.9/bin/linux/$TARGETARCH/go-template || { echo "Failed to download go-template"; exit 1; } \
   && mkdir -m 777 -p client-tools/harness-pywinrm/v0.4-dev \
   && curl -f -s -L -o client-tools/harness-pywinrm/v0.4-dev/harness-pywinrm https://app.harness.io/public/shared/tools/harness-pywinrm/release/v0.4-dev/bin/linux/$TARGETARCH/harness-pywinrm || { echo "Failed to download harness-pywinrm"; exit 1; } \
   && mkdir -m 777 -p client-tools/chartmuseum/v0.16.3 \
@@ -73,7 +73,7 @@ RUN set -o pipefail \
   && chown -R 1001 $JAVA_HOME/lib/security/cacerts
 
 ENV PATH=/opt/harness-delegate/client-tools/kubectl/v1.28.7/:$PATH
-ENV PATH=/opt/harness-delegate/client-tools/go-template/v0.4.8/:$PATH
+ENV PATH=/opt/harness-delegate/client-tools/go-template/v0.4.9/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/chartmuseum/v0.16.3/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/tf-config-inspect/v1.3/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/helm/v3.13.3/:$PATH
@@ -82,7 +82,7 @@ ENV PATH=/opt/harness-delegate/client-tools/oc/v4.17.30/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/kubelogin/v0.1.9/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/harness-credentials-plugin/v0.1.1/:$PATH
 
-RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar
+RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar && [ $(stat -c%s delegate.jar) -ge 104857600 ] || (echo "Failed to download delegate.jar or delegate.jar is corrupted" && exit 1)
 
 USER 1001
 
