Syncing docker file for 85601

diff --git a/Dockerfile-minimal b/Dockerfile-minimal
--- a/Dockerfile-minimal
+++ b/Dockerfile-minimal
@@ -42,8 +42,8 @@ COPY --from=eclipse-temurin:17.0.13_11-jre-ubi9-minimal /opt/java/openjdk/ /opt/
 ENV JAVA_HOME=/opt/java/openjdk
 
 RUN set -o pipefail \
-  && mkdir -m 777 -p client-tools/scm/45f06d0e2 \
-  && curl -f -s -L -o client-tools/scm/45f06d0e2/scm https://app.harness.io/public/shared/tools/scm/release/45f06d0e2/bin/linux/$TARGETARCH/scm || { echo "Failed to download scm"; exit 1; } \
+  && mkdir -m 777 -p client-tools/scm/182cd06f7 \
+  && curl -f -s -L -o client-tools/scm/182cd06f7/scm https://app.harness.io/public/shared/tools/scm/release/182cd06f7/bin/linux/$TARGETARCH/scm || { echo "Failed to download scm"; exit 1; } \
   && curl -f -s -L -o $JAVA_HOME/bin/jattach https://app.harness.io/public/shared/tools/jattach/release/v2.2/bin/linux/$TARGETARCH/jattach || { echo "Failed to download jattach"; exit 1; } \
   && chmod +x $JAVA_HOME/bin/jattach \
   && chmod -R 775 /opt/harness-delegate \
@@ -61,5 +61,7 @@ ENV PATH="$JAVA_HOME/bin/jattach:${PATH}"
 RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar
 
 USER 1001
+
+HEALTHCHECK --interval=10s --timeout=1s --start-period=10s --retries=3 CMD curl --fail http://localhost:3460/api/health
 
 CMD [ "./start.sh" ]
