Syncing docker file for 84800

diff --git a/Dockerfile-minimal b/Dockerfile-minimal
--- a/Dockerfile-minimal
+++ b/Dockerfile-minimal
@@ -3,11 +3,14 @@
 # that can be found in the licenses directory at the root of this repository, also available at
 # https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
 
-FROM redhat/ubi8-minimal:8.10
+FROM redhat/ubi9-minimal:9.4
 
 LABEL name="harness/delegate-minimal" \
       vendor="Harness" \
       maintainer="Harness"
+
+RUN echo -e '#!/bin/sh\nexec /usr/bin/microdnf -y "$@"' > /usr/local/bin/microdnf \
+  && chmod +x /usr/local/bin/microdnf
 
 RUN microdnf update --nodocs --setopt=install_weak_deps=0 \
   && microdnf install --nodocs \
@@ -39,8 +42,8 @@ COPY --from=eclipse-temurin:17.0.11_9-jre-ubi9-minimal /opt/java/openjdk/ /opt/j
 ENV JAVA_HOME=/opt/java/openjdk
 
 RUN set -o pipefail \
-  && mkdir -m 777 -p client-tools/scm/f52a6de3e \
-  && curl -f -s -L -o client-tools/scm/f52a6de3e/scm https://app.harness.io/public/shared/tools/scm/release/f52a6de3e/bin/linux/$TARGETARCH/scm || { echo "Failed to download scm"; exit 1; } \
+  && mkdir -m 777 -p client-tools/scm/9ac47f795 \
+  && curl -f -s -L -o client-tools/scm/9ac47f795/scm https://app.harness.io/public/shared/tools/scm/release/9ac47f795/bin/linux/$TARGETARCH/scm || { echo "Failed to download scm"; exit 1; } \
   && curl -f -s -L -o $JAVA_HOME/bin/jattach https://app.harness.io/public/shared/tools/jattach/release/v2.2/bin/linux/$TARGETARCH/jattach || { echo "Failed to download jattach"; exit 1; } \
   && chmod +x $JAVA_HOME/bin/jattach \
   && chmod -R 775 /opt/harness-delegate \
