Syncing docker file for 83802

diff --git a/Dockerfile-minimal b/Dockerfile-minimal
--- a/Dockerfile-minimal
+++ b/Dockerfile-minimal
@@ -30,26 +30,26 @@ COPY immutable-scripts /opt/harness-delegate/
 WORKDIR /opt/harness-delegate
 
 ARG TARGETARCH
+ENV TARGETARCH=${TARGETARCH:-amd64}
 ARG BASEURL=https://app.harness.io/public/shared/delegates
 ARG DELEGATEVERSION
 
 COPY --from=eclipse-temurin:17.0.7_7-jre-ubi9-minimal /opt/java/openjdk/ /opt/java/openjdk/
 ENV JAVA_HOME=/opt/java/openjdk/
 
-RUN mkdir -m 777 -p client-tools/scm/2f24e4b26 \
-  && curl -s -L -o client-tools/scm/2f24e4b26/scm https://app.harness.io/public/shared/tools/scm/release/2f24e4b26/bin/linux/$TARGETARCH/scm \
+RUN set -o pipefail \
+  && mkdir -m 777 -p client-tools/scm/e92737411 \
+  && curl -f -s -L -o client-tools/scm/e92737411/scm https://app.harness.io/public/shared/tools/scm/release/e92737411/bin/linux/$TARGETARCH/scm || { echo "Failed to download scm"; exit 1; } \
   && chmod -R 775 /opt/harness-delegate \
   && chgrp -R 0 /opt/harness-delegate \
   && chown -R 1001 /opt/harness-delegate \
   && chown -R 1001 $JAVA_HOME/lib/security/cacerts
-RUN mkdir -p /opt/harness-delegate/additional_certs_pem_split
 
 ENV LANG=en_US.UTF-8
 ENV HOME=/opt/harness-delegate
 ENV CLIENT_TOOLS_DOWNLOAD_DISABLED=true
 ENV INSTALL_CLIENT_TOOLS_IN_BACKGROUND=true
 ENV PATH="$JAVA_HOME/bin:${PATH}"
-ENV SHARED_CA_CERTS_PATH=/opt/harness-delegate/additional_certs_pem_split
 
 RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar
 
diff --git a/Dockerfile-ubuntu b/Dockerfile-ubuntu
--- a/Dockerfile-ubuntu
+++ b/Dockerfile-ubuntu
@@ -29,8 +29,6 @@ COPY immutable-scripts /opt/harness-delegate/
 
 WORKDIR /opt/harness-delegate
 
-RUN mkdir -p /opt/harness-delegate/additional_certs_pem_split
-
 COPY --from=eclipse-temurin:17.0.7_7-jre /opt/java/openjdk/ /opt/java/openjdk/
 
 ENV LANG=en_US.UTF-8
@@ -44,28 +42,29 @@ ARG TARGETARCH
 ARG BASEURL=https://app.harness.io/public/shared/delegates
 ARG DELEGATEVERSION
 
-RUN mkdir -m 777 -p client-tools/kubectl/v1.28.7 \
-  && curl -s -L -o client-tools/kubectl/v1.28.7/kubectl https://app.harness.io/public/shared/tools/kubectl/release/v1.28.7/bin/linux/$TARGETARCH/kubectl \
+RUN set -o pipefail \
+  && mkdir -m 777 -p client-tools/kubectl/v1.28.7 \
+  && curl -f -s -L -o client-tools/kubectl/v1.28.7/kubectl https://app.harness.io/public/shared/tools/kubectl/release/v1.28.7/bin/linux/$TARGETARCH/kubectl || { echo "Failed to download kubectl"; exit 1; } \
   && mkdir -m 777 -p client-tools/helm/v3.12.0 \
-  && curl -s -L -o client-tools/helm/v3.12.0/helm https://app.harness.io/public/shared/tools/helm/release/v3.12.0/bin/linux/$TARGETARCH/helm \
+  && curl -f -s -L -o client-tools/helm/v3.12.0/helm https://app.harness.io/public/shared/tools/helm/release/v3.12.0/bin/linux/$TARGETARCH/helm || { echo "Failed to download helm"; exit 1; } \
   && mkdir -m 777 -p client-tools/go-template/v0.4.5 \
-  && curl -s -L -o client-tools/go-template/v0.4.5/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4.5/bin/linux/$TARGETARCH/go-template \
+  && curl -f -s -L -o client-tools/go-template/v0.4.5/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4.5/bin/linux/$TARGETARCH/go-template || { echo "Failed to download go-template"; exit 1; } \
   && mkdir -m 777 -p client-tools/harness-pywinrm/v0.4-dev \
-  && curl -s -L -o client-tools/harness-pywinrm/v0.4-dev/harness-pywinrm https://app.harness.io/public/shared/tools/harness-pywinrm/release/v0.4-dev/bin/linux/$TARGETARCH/harness-pywinrm \
+  && curl -f -s -L -o client-tools/harness-pywinrm/v0.4-dev/harness-pywinrm https://app.harness.io/public/shared/tools/harness-pywinrm/release/v0.4-dev/bin/linux/$TARGETARCH/harness-pywinrm || { echo "Failed to download harness-pywinrm"; exit 1; } \
   && mkdir -m 777 -p client-tools/chartmuseum/v0.15.0 \
-  && curl -s -L -o client-tools/chartmuseum/v0.15.0/chartmuseum https://app.harness.io/public/shared/tools/chartmuseum/release/v0.15.0/bin/linux/$TARGETARCH/chartmuseum \
+  && curl -f -s -L -o client-tools/chartmuseum/v0.15.0/chartmuseum https://app.harness.io/public/shared/tools/chartmuseum/release/v0.15.0/bin/linux/$TARGETARCH/chartmuseum || { echo "Failed to download chartmuseum"; exit 1; } \
   && mkdir -m 777 -p client-tools/tf-config-inspect/v1.2 \
-  && curl -s -L -o client-tools/tf-config-inspect/v1.2/terraform-config-inspect https://app.harness.io/public/shared/tools/terraform-config-inspect/v1.2/linux/$TARGETARCH/terraform-config-inspect \
-  && mkdir -m 777 -p client-tools/oc/v4.13.32 \
-  && curl -s -L -o client-tools/oc/v4.13.32/oc https://app.harness.io/public/shared/tools/oc/release/v4.13.32/bin/linux/$TARGETARCH/oc \
-  && mkdir -m 777 -p client-tools/scm/2f24e4b26 \
-  && curl -s -L -o client-tools/scm/2f24e4b26/scm https://app.harness.io/public/shared/tools/scm/release/2f24e4b26/bin/linux/$TARGETARCH/scm \
+  && curl -f -s -L -o client-tools/tf-config-inspect/v1.2/terraform-config-inspect https://app.harness.io/public/shared/tools/terraform-config-inspect/v1.2/linux/$TARGETARCH/terraform-config-inspect || { echo "Failed to download terraform-config-inspect"; exit 1; } \
+  && mkdir -m 777 -p client-tools/oc/v4.15.25 \
+  && curl -f -s -L -o client-tools/oc/v4.15.25/oc https://app.harness.io/public/shared/tools/oc/release/v4.15.25/bin/linux/$TARGETARCH/oc || { echo "Failed to download oc"; exit 1; } \
+  && mkdir -m 777 -p client-tools/scm/e92737411 \
+  && curl -f -s -L -o client-tools/scm/e92737411/scm https://app.harness.io/public/shared/tools/scm/release/e92737411/bin/linux/$TARGETARCH/scm || { echo "Failed to download scm"; exit 1; } \
   && mkdir -m 777 -p client-tools/kubelogin/v0.1.1 \
-  && curl -s -L -o client-tools/kubelogin/v0.1.1/kubelogin https://app.harness.io/public/shared/tools/kubelogin/release/v0.1.1/bin/linux/$TARGETARCH/kubelogin \
+  && curl -f -s -L -o client-tools/kubelogin/v0.1.1/kubelogin https://app.harness.io/public/shared/tools/kubelogin/release/v0.1.1/bin/linux/$TARGETARCH/kubelogin || { echo "Failed to download kubelogin"; exit 1; } \
   && mkdir -m 777 -p client-tools/harness-credentials-plugin/v0.1.0 \
-  && curl -s -L -o client-tools/harness-credentials-plugin/v0.1.0/harness-credentials-plugin https://app.harness.io/public/shared/tools/harness-credentials-plugin/release/v0.1.0/bin/linux/$TARGETARCH/harness-credentials-plugin \
+  && curl -f -s -L -o client-tools/harness-credentials-plugin/v0.1.0/harness-credentials-plugin https://app.harness.io/public/shared/tools/harness-credentials-plugin/release/v0.1.0/bin/linux/$TARGETARCH/harness-credentials-plugin || { echo "Failed to download harness-credentials-plugin"; exit 1; } \
   && chmod -R 775 /opt/harness-delegate \
-  && chgrp -R 0 /opt/harness-delegate  \
+  && chgrp -R 0 /opt/harness-delegate \
   && chown -R 1001 /opt/harness-delegate \
   && chown -R 1001 $JAVA_HOME/lib/security/cacerts
 
@@ -74,10 +73,9 @@ ENV PATH=/opt/harness-delegate/client-tools/go-template/v0.4.5/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/chartmuseum/v0.15.0/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/tf-config-inspect/v1.2/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/helm/v3.12.0/:$PATH
-ENV PATH=/opt/harness-delegate/client-tools/oc/v4.13.32/:$PATH
+ENV PATH=/opt/harness-delegate/client-tools/oc/v4.15.25/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/kubelogin/v0.1.1/:$PATH
 ENV PATH=/opt/harness-delegate/client-tools/harness-credentials-plugin/v0.1.0/:$PATH
-ENV SHARED_CA_CERTS_PATH=/opt/harness-delegate/additional_certs_pem_split
 
 RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar
 
